sudo: true
language: cpp
group: deprecated-2017Q3

os:
  - linux
  - osx

compiler:
  - gcc
  - clang
  
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install pcl sqlite octomap ceres-solver; fi
  
matrix:
  include:
    - os: linux
      dist: trusty
      install:
        - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu trusty main" > /etc/apt/sources.list.d/ros-latest.list'
        - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
        - sudo apt-get update
        - sudo apt-get update && sudo apt-get install dpkg
        - sudo apt-get -y install ros-indigo-rtabmap-ros
        - sudo apt-get -y remove ros-indigo-rtabmap

      before_script: 
        - source /opt/ros/indigo/setup.bash

    - os: linux
      dist: xenial
      install:
        - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu xenial main" > /etc/apt/sources.list.d/ros-latest.list'
        - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
        - sudo apt-get update
        - sudo apt-get update && sudo apt-get install dpkg
        - sudo apt-get -y install ros-kinetic-rtabmap-ros
        - sudo apt-get -y remove ros-kinetic-rtabmap

      before_script: 
        - source /opt/ros/kinetic/setup.bash

    - os: linux
      dist: bionic
      install:
        - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu bionic main" > /etc/apt/sources.list.d/ros-latest.list'
        - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
        - sudo apt-get update
        - sudo apt-get update && sudo apt-get install dpkg
        - sudo apt-get -y install ros-melodic-rtabmap-ros
        - sudo apt-get -y remove ros-melodic-rtabmap

      before_script: 
        - source /opt/ros/melodic/setup.bash
        
    - os: linux
      dist: focal
      install:
        - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu focal main" > /etc/apt/sources.list.d/ros-latest.list'
        - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
        - sudo apt-get update
        - sudo apt-get update && sudo apt-get install dpkg
        - sudo apt-get -y install ros-noetic-rtabmap-ros
        - sudo apt-get -y remove ros-noetic-rtabmap

      before_script: 
        - source /opt/ros/noetic/setup.bash

script:
  - mkdir -p build && cd build
  - cmake .. 
  - make

notifications:
  email:
    - matlabbe@gmail.com
