name: docker

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        docker_tag: [xenial, bionic, focal, android24, android26]
        include:
        - docker_tag: xenial
          docker_path: 'xenial'
        - docker_tag: bionic
          docker_path: 'bionic'
        - docker_tag: focal
          docker_path: 'focal'
        - docker_tag: android24
          docker_path: 'bionic/android/rtabmap_api24'
        - docker_tag: android26
          docker_path: 'bionic/android/rtabmap_api26'
    
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./docker/${{ matrix.docker_path }}
          push: true
          tags: introlab3it/rtabmap:${{ matrix.docker_tag }}
          cache-from: type=registry,ref=introlab3it/rtabmap:buildcache_${{ matrix.docker_tag }}
          cache-to: type=registry,ref=introlab3it/rtabmap:buildcache_${{ matrix.docker_tag }},mode=max

